name: 'Parse Trivy Report'
description: 'Parses a Trivy JSON report and prints relevant fields'

inputs:
  trivy-report:
    description: 'Path to the Trivy JSON report'
    required: true

runs:
  using: 'node16'  # Usa Node.js 16 o successivo
  steps:
    - run: npm install  # Installa le dipendenze come semver e axios
      shell: bash  # Specifica la shell da usare
    - run: node index.js  # Esegui il file index.js
      shell: bash  # Specifica la shell da usare
